'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property id As Integer
    Public Property isPrivate As Boolean
    Public Property name As String
    Public Property careOf As String
    Public Property address1 As String

    Public Overridable Property Zip As Zip
    Public Overridable Property Customers As ObservableListSource(Of Customer) = New ObservableListSource(Of Customer)
    Public Overridable Property Employees As ObservableListSource(Of Employee) = New ObservableListSource(Of Employee)
    Public Overridable Property Orders As ObservableListSource(Of Order) = New ObservableListSource(Of Order)

End Class
