'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class address
    Public Property id As Integer
    Public Property isPrivate As Boolean
    Public Property name As String
    Public Property careOf As String
    Public Property address1 As String
    Public Property zip As Integer

    Public Overridable Property zip1 As zip
    Public Overridable Property customers As ICollection(Of customer) = New HashSet(Of customer)
    Public Overridable Property employees As ICollection(Of employee) = New HashSet(Of employee)
    Public Overridable Property orders As ICollection(Of order) = New HashSet(Of order)

End Class
