'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property id As Integer
    Public Property isPrivate As SByte
    Public Property name As String
    Public Property phone As String
    Public Property email As String
    Public Property addressId As Integer
    Public Property customerTypeId As Integer
    Public Property discountPlanId As Integer
    Public Property note As String
    Public Property created As Nullable(Of Date)
    Public Property modfied As Nullable(Of Date)

    Public Overridable Property Address As Address
    Public Overridable Property CustomerType As CustomerType
    Public Overridable Property DiscountPlan As DiscountPlan
    Public Overridable Property Orders As ObservableListSource(Of Order) = New ObservableListSource(Of Order)

End Class
