'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class deliveryMethod
    Public Property id As Integer
    Public Property name As String
    Public Property price As Decimal
    Public Property isFixedPrice As Boolean

    Public Overridable Property orders As ObservableListSource(Of order) = New ObservableListSource(Of order)

End Class
