'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee_has_roles
    Public Property id As Integer
    Public Property roleId As Integer
    Public Property employeeId As Integer

    Public Overridable Property employee As employee
    Public Overridable Property role As role

End Class
