'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property id As Integer
    Public Property name As String
    Public Property phoneId As Integer
    Public Property addressId As Integer
    Public Property email As String
    Public Property password As String

    Public Overridable Property address As address
    Public Overridable Property phone As phone
    Public Overridable Property orders As ICollection(Of order) = New HashSet(Of order)
    Public Overridable Property roles As ICollection(Of role) = New HashSet(Of role)

End Class
