'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [event]
    Public Property eventsId As Integer
    Public Property eventName As String
    Public Property eventTime As Date
    Public Property employeeId As Integer
    Public Property eventData As String

End Class
