'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ingredient
    Public Property id As Integer
    Public Property name As String
    Public Property description As String
    Public Property kilocaloriesPerUnit As Double
    Public Property vat As Integer
    Public Property published As Nullable(Of Boolean)

    Public Overridable Property Batches As ObservableListSource(Of Batch) = New ObservableListSource(Of Batch)
    Public Overridable Property RecipeLines As ObservableListSource(Of RecipeLine) = New ObservableListSource(Of RecipeLine)
    Public Overridable Property Unit As Unit
    Public Overridable Property IngredientPrices As ObservableListSource(Of IngredientPrice) = New ObservableListSource(Of IngredientPrice)
    Public Overridable Property OrderLines As ObservableListSource(Of OrderLine) = New ObservableListSource(Of OrderLine)

End Class
