'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ingredientPrice
    Public Property id As Integer
    Public Property [date] As Date
    Public Property markUpPercentage As Double

    Public Overridable Property ingredient As ingredient

End Class
