'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ingredient
    Public Property id As Integer
    Public Property name As String
    Public Property description As String
    Public Property kilocaloriesPerUnit As Double
    Public Property vat As Integer
    Public Property unitId As Integer
    Public Property published As Nullable(Of Boolean)

    Public Overridable Property batches As ICollection(Of batch) = New HashSet(Of batch)
    Public Overridable Property cake_has_ingredient As ICollection(Of cake_has_ingredient) = New HashSet(Of cake_has_ingredient)
    Public Overridable Property unit As unit
    Public Overridable Property ingredientPrices As ICollection(Of ingredientPrice) = New HashSet(Of ingredientPrice)
    Public Overridable Property order_has_ingredient As ICollection(Of order_has_ingredient) = New HashSet(Of order_has_ingredient)

End Class
