'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Db
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Db")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property Batches() As DbSet(Of Batch)
    Public Overridable Property Cakes() As DbSet(Of Cake)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property CustomerTypes() As DbSet(Of CustomerType)
    Public Overridable Property DeliveryMethods() As DbSet(Of DeliveryMethod)
    Public Overridable Property DiscountPlans() As DbSet(Of DiscountPlan)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property FrequencyTypes() As DbSet(Of FrequencyType)
    Public Overridable Property Ingredients() As DbSet(Of Ingredient)
    Public Overridable Property IngredientPrices() As DbSet(Of IngredientPrice)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property OrderLines() As DbSet(Of OrderLine)
    Public Overridable Property Phones() As DbSet(Of Phone)
    Public Overridable Property RecipeLines() As DbSet(Of RecipeLine)
    Public Overridable Property Roles() As DbSet(Of Role)
    Public Overridable Property Subscriptions() As DbSet(Of Subscription)
    Public Overridable Property SystemEvents() As DbSet(Of SystemEvent)
    Public Overridable Property Units() As DbSet(Of Unit)
    Public Overridable Property Zips() As DbSet(Of Zip)

End Class
