Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel
Imports System.Diagnostics.CodeAnalysis
Imports System.Data.Entity

''' <summary>
''' Collection properties must implement the IListSource interface to enable two-way data binding with sorting when using Windows Forms. 
''' To do this we are going to extend ObservableCollection to add IListSource functionality.
''' 
''' This class enables two-way data binding as well as sorting. The class derives from ObservableCollection&lt;T> 
''' and adds an explicit implementation of IListSource. The GetList() method of IListSource is implemented to 
''' return an IBindingList implementation that stays in sync with the ObservableCollection. 
''' The IBindingList implementation generated by ToBindingList supports sorting. The ToBindingList extention 
''' method is defined in the EntityFramework assembly.
''' 
''' See also http://msdn.microsoft.com/en-us/data/jj682076.aspx
''' </summary>
''' <typeparam name="T"></typeparam>
''' <remarks></remarks>
Public Class ObservableListSource(Of T As Class)
    Inherits ObservableCollection(Of T)
    Implements IListSource
    Private _bindingList As IBindingList

    Private ReadOnly Property IListSource_ContainsListCollection() As Boolean Implements IListSource.ContainsListCollection
        Get
            Return False
        End Get
    End Property

    Private Function IListSource_GetList() As IList Implements IListSource.GetList
        If _bindingList Is Nothing Then
            Return Me.ToBindingList()
        Else
            Return _bindingList
        End If
    End Function
End Class