'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order_has_ingredient
    Public Property id As Integer
    Public Property order_id As Integer
    Public Property ingredient_id As Integer
    Public Property amount As Double
    Public Property cakeId As Nullable(Of Integer)

    Public Overridable Property ingredient As ingredient
    Public Overridable Property order As order

End Class
