'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order
    Public Property id As Integer
    Public Property customerId As Integer
    Public Property deliveryAddressId As Integer
    Public Property deliveryPhone As String
    Public Property deliveryEmail As String
    Public Property deliveryMethodId As Integer
    Public Property employeeId As Integer
    Public Property subscriptionId As Nullable(Of Integer)
    Public Property discountPercentage As Nullable(Of Integer)
    Public Property discountAbsolute As Nullable(Of Decimal)
    Public Property note As String
    Public Property amountPayed As Decimal
    Public Property sent As Nullable(Of Date)
    Public Property settled As Nullable(Of Date)
    Public Property exported As Nullable(Of Date)
    Public Property created As Date
    Public Property modified As Date
    Public Property isSubscriptionOrder As Boolean

    Public Overridable Property address As address
    Public Overridable Property customer As customer
    Public Overridable Property deliveryMethod As deliveryMethod
    Public Overridable Property employee As employee
    Public Overridable Property order_has_ingredient As ICollection(Of order_has_ingredient) = New HashSet(Of order_has_ingredient)
    Public Overridable Property subscriptions As ICollection(Of subscription) = New HashSet(Of subscription)

End Class
