'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderLine
    Public Property id As Integer
    Public Property orderId As Integer
    Public Property ingredientId As Integer
    Public Property amount As Double
    Public Property totalPrice As Nullable(Of Decimal)
    Public Property cakeId As Nullable(Of Integer)

    Public Overridable Property Ingredient As Ingredient
    Public Overridable Property Order As Order

End Class
