'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class phone
    Public Property id As Integer
    Public Property countryprefix As Nullable(Of Integer)
    Public Property phonenumber As String

    Public Overridable Property employees As ICollection(Of employee) = New HashSet(Of employee)

End Class
