'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class role
    Public Property id As Integer
    Public Property name As String

    Public Overridable Property employee_has_roles As ICollection(Of employee_has_roles) = New HashSet(Of employee_has_roles)

End Class
