'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class unit
    Public Property id As Integer
    Public Property name As String

    Public Overridable Property ingredients As ICollection(Of ingredient) = New HashSet(Of ingredient)

End Class
