'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zip
    Public Property zip1 As Integer
    Public Property city As String

    Public Overridable Property addresses As ObservableListSource(Of address) = New ObservableListSource(Of address)

End Class
