'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property id As Integer
    Public Property firstName As String
    Public Property lastName As String
    Public ReadOnly Property fullName As String
        Get
            Return firstName & " " & lastName
        End Get
    End Property
    Public Property email As String
    Public Property password As String

    Public Overridable Property Address As Address
    Public Overridable Property Phone As Phone
    Public Overridable Property Orders As ObservableListSource(Of Order) = New ObservableListSource(Of Order)
    Public Overridable Property Roles As ObservableListSource(Of Role) = New ObservableListSource(Of Role)

End Class
