'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cake
    Public Property id As Integer
    Public Property name As String
    Public Property recipe As String
    Public Property markupPercentage As Nullable(Of Double)
    Public Property deleted As Nullable(Of Date)
    Public Property published As Nullable(Of Boolean)

    Public Overridable Property RecipeLines As ObservableListSource(Of RecipeLine) = New ObservableListSource(Of RecipeLine)

End Class
